on: 
  workflow_dispatch:
jobs:
   build:
     name: build 
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2.5.0
       - name: Step1
         run: echo Hello, world!
#        uses: bitoiu/node-js-action-template@v1.0
       - name: add file
         run: touch package.json
       - name: Workspace Commit
         uses: gha-utilities/workspace-commit@v0.0.3
         message: update file 
     
