on: 
  workflow_dispatch:
jobs:
   build:
     name: build 
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2.5.0
       - name: Step1
         run: echo Hello, world!
#        uses: bitoiu/node-js-action-template@v1.0
       - name: add file
         run: cat "{}" > package.json
       - name: Workspace Commit
         uses: EndBug/add-and-commit@v9
         with:
           author_name: vaniship
           author_email: vaniship@gmail.com
           message: "AUTO GENERATE README"
           add: "*.json"     
#        run: |
#          touch package.json
#          git add .
#          git commit -m "chore: update file"
#       - name: Workspace Commit
#         uses: gha-utilities/workspace-commit@v0.0.3
#         with:
#           message: update file 
     
